# Generated by Django 5.0.6 on 2024-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0007_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commentaire',
            field=models.TextField(default=0),
        ),
    ]
