# Generated by Django 5.0.6 on 2024-09-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0008_commande_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='pays',
        ),
    ]
