# Generated by Django 5.0.6 on 2024-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0010_rename_title_produit_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
