# Generated by Django 5.0.6 on 2024-09-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0011_alter_produit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom',
            new_name='title',
        ),
    ]
