# Generated by Django 5.0.6 on 2024-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0013_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='item',
            new_name='produits_co',
        ),
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
