# Generated by Django 5.0.6 on 2024-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0014_rename_item_commande_produits_co_alter_commande_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='produits_co',
            new_name='item',
        ),
    ]
