# Generated by Django 5.0.6 on 2024-09-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steakhouse', '0015_rename_produits_co_commande_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='adresse',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='ville',
            new_name='zone',
        ),
    ]
